<a href="https://colab.research.google.com/github/Hurri301/Advanced-Computational-Techniques-for-Big-Imaging-and-Signal-Data/blob/main/Titanic_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
import numpy as np
import sklearn.ensemble
import sklearn.preprocessing
import sklearn.metrics
from sklearn.model_selection import train_test_split

In [43]:
# load csv
df = pd.read_csv('titanic.csv')
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [44]:
import pandas as pd
df.drop(columns=['Name', 'Ticket', 'Cabin'], inplace=True)

In [45]:
df = pd.concat([df,pd.get_dummies(df['Embarked'],prefix='Embarked')],
axis=1)
df = df.drop('Embarked', axis=1)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,male,22.0,1,0,7.2500,False,False,True
1,2,1,1,female,38.0,1,0,71.2833,True,False,False
2,3,1,3,female,26.0,0,0,7.9250,False,False,True
3,4,1,1,female,35.0,1,0,53.1000,False,False,True
4,5,0,3,male,35.0,0,0,8.0500,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,13.0000,False,False,True
887,888,1,1,female,19.0,0,0,30.0000,False,False,True
888,889,0,3,female,NaN,1,2,23.4500,False,False,True
889,890,1,1,male,26.0,0,0,30.0000,True,False,False
890,891,0,3,male,32.0,0,0,7.7500,False,True,False

In [46]:
print(df.shape)
df.dtypes

(891, 11)

PassengerId      int64
Survived         int64
Pclass           int64
Sex             object
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked_C        bool
Embarked_Q        bool
Embarked_S        bool
dtype: object

In [47]:
# convert all types
df = df.convert_dtypes()
print(df.dtypes)

PassengerId             Int64
Survived                Int64
Pclass                  Int64
Sex            string[python]
Age                   Float64
SibSp                   Int64
Parch                   Int64
Fare                  Float64
Embarked_C            boolean
Embarked_Q            boolean
Embarked_S            boolean
dtype: object

In [48]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked_C       0
Embarked_Q       0
Embarked_S       0
dtype: int64

In [49]:
df.isna().sum() / len(df) * 100

PassengerId     0.00000
Survived        0.00000
Pclass          0.00000
Sex             0.00000
Age            19.86532
SibSp           0.00000
Parch           0.00000
Fare            0.00000
Embarked_C      0.00000
Embarked_Q      0.00000
Embarked_S      0.00000
dtype: float64

In [50]:
df.dropna(axis=0)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,male,22.0,1,0,7.25,False,False,True
1,2,1,1,female,38.0,1,0,71.2833,True,False,False
2,3,1,3,female,26.0,0,0,7.925,False,False,True
3,4,1,1,female,35.0,1,0,53.1,False,False,True
4,5,0,3,male,35.0,0,0,8.05,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,female,39.0,0,5,29.125,False,True,False
886,887,0,2,male,27.0,0,0,13.0,False,False,True
887,888,1,1,female,19.0,0,0,30.0,False,False,True
889,890,1,1,male,26.0,0,0,30.0,True,False,False
890,891,0,3,male,32.0,0,0,7.75,False,True,False

In [51]:
# case 2
df.dropna(axis=1)

,PassengerId,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,male,1,0,7.25,False,False,True
1,2,1,1,female,1,0,71.2833,True,False,False
2,3,1,3,female,0,0,7.925,False,False,True
3,4,1,1,female,1,0,53.1,False,False,True
4,5,0,3,male,0,0,8.05,False,False,True
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,0,0,13.0,False,False,True
887,888,1,1,female,0,0,30.0,False,False,True
888,889,0,3,female,1,2,23.45,False,False,True
889,890,1,1,male,0,0,30.0,True,False,False
890,891,0,3,male,0,0,7.75,False,True,False

In [52]:
df.dropna(thresh=0.8*len(df),axis=1)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,male,22.0,1,0,7.25,False,False,True
1,2,1,1,female,38.0,1,0,71.2833,True,False,False
2,3,1,3,female,26.0,0,0,7.925,False,False,True
3,4,1,1,female,35.0,1,0,53.1,False,False,True
4,5,0,3,male,35.0,0,0,8.05,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,13.0,False,False,True
887,888,1,1,female,19.0,0,0,30.0,False,False,True
888,889,0,3,female,<NA>,1,2,23.45,False,False,True
889,890,1,1,male,26.0,0,0,30.0,True,False,False
890,891,0,3,male,32.0,0,0,7.75,False,True,False

In [53]:
# get columns containing booleans
boolean_cols = df.select_dtypes(include=bool).columns.tolist()
boolean_cols

['Embarked_C', 'Embarked_Q', 'Embarked_S']

In [54]:
# get most frequent values
most_frequent_values = df[boolean_cols].mode().loc[0]

# replace missing content with mode
df[boolean_cols] = df[boolean_cols].fillna(most_frequent_values)

df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,male,22.0,1,0,7.25,False,False,True
1,2,1,1,female,38.0,1,0,71.2833,True,False,False
2,3,1,3,female,26.0,0,0,7.925,False,False,True
3,4,1,1,female,35.0,1,0,53.1,False,False,True
4,5,0,3,male,35.0,0,0,8.05,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,13.0,False,False,True
887,888,1,1,female,19.0,0,0,30.0,False,False,True
888,889,0,3,female,<NA>,1,2,23.45,False,False,True
889,890,1,1,male,26.0,0,0,30.0,True,False,False
890,891,0,3,male,32.0,0,0,7.75,False,True,False

In [55]:
# get columns containing numbers
numeric = df.select_dtypes(include=int)
integer_columns = numeric.columns
# print them
integer_columns

Index(['PassengerId', 'Survived', 'Pclass', 'SibSp', 'Parch'], dtype='object')

In [56]:
# replace these columns with their median
median_of_integer_cols = df[integer_columns].median()
df[integer_columns] = df[integer_columns].fillna(median_of_integer_cols)

In [57]:
# get columns containing numbers
# numeric = df.select_dtypes(include=np.number)
numeric = df.select_dtypes(include=float)
numeric_columns = numeric.columns
# print them
numeric_columns

Index(['Age', 'Fare'], dtype='object')

In [58]:
# replace these columns with their median
# median_of_numeric_cols = df[numeric_columns].median()
# df[numeric_columns] = df[numeric_columns].fillna(median_of_numeric_cols)

# convert all floats64 to floats
df[numeric_columns] = df[numeric_columns].astype(float)

# interpolate
df[numeric_columns] = df[numeric_columns].interpolate(method ='linear')

In [59]:
# get categorical columns
categorical_columns = df.select_dtypes(include='string').columns.tolist()
print(categorical_columns)

['Sex']

In [60]:
# let's get the most frequent values
most_frequent_values = df[categorical_columns].mode()
most_frequent_values

    Sex
0  male

In [61]:
df[categorical_columns] = df[categorical_columns].fillna(most_frequent_values)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,male,22.0,1,0,7.2500,False,False,True
1,2,1,1,female,38.0,1,0,71.2833,True,False,False
2,3,1,3,female,26.0,0,0,7.9250,False,False,True
3,4,1,1,female,35.0,1,0,53.1000,False,False,True
4,5,0,3,male,35.0,0,0,8.0500,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,13.0000,False,False,True
887,888,1,1,female,19.0,0,0,30.0000,False,False,True
888,889,0,3,female,22.5,1,2,23.4500,False,False,True
889,890,1,1,male,26.0,0,0,30.0000,True,False,False
890,891,0,3,male,32.0,0,0,7.7500,False,True,False

In [62]:
# final check
df.isnull().values.any()

False

In [63]:
# initialize label encoder
le = sklearn.preprocessing.LabelEncoder()

# encode target class
df['Embarked_S'] = le.fit_transform(df['Embarked_S'])

In [64]:
# get columns containing cathegorical features
categorical_features = df.select_dtypes(include='string').columns.tolist()
categorical_features

['Sex']

In [65]:
# one-hot encode these features
df = pd.get_dummies(df, prefix=categorical_features)
df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Sex_female,Sex_male
0,1,0,3,22.0,1,0,7.2500,False,False,1,False,True
1,2,1,1,38.0,1,0,71.2833,True,False,0,True,False
2,3,1,3,26.0,0,0,7.9250,False,False,1,True,False
3,4,1,1,35.0,1,0,53.1000,False,False,1,True,False
4,5,0,3,35.0,0,0,8.0500,False,False,1,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,27.0,0,0,13.0000,False,False,1,False,True
887,888,1,1,19.0,0,0,30.0000,False,False,1,True,False
888,889,0,3,22.5,1,2,23.4500,False,False,1,True,False
889,890,1,1,26.0,0,0,30.0000,True,False,0,False,True
890,891,0,3,32.0,0,0,7.7500,False,True,0,False,True

In [66]:
# initialize forest
isoforest = sklearn.ensemble.IsolationForest(n_estimators=1000, contamination=0.01, random_state=0)
# for each sample, get anomaly score
res = isoforest.fit_predict(df.to_numpy())

In [67]:
df[res==-1]

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Sex_female,Sex_male
16,17,0,3,2.0,4,1,29.1250,False,True,0,False,True
27,28,0,1,19.0,3,2,263.0000,False,False,1,False,True
171,172,0,3,4.0,4,1,29.1250,False,True,0,False,True
311,312,1,1,18.0,2,2,262.3750,True,False,0,True,False
438,439,0,1,64.0,1,4,263.0000,False,False,1,False,True
679,680,1,1,36.0,0,1,512.3292,True,False,0,False,True
742,743,1,1,21.0,2,2,262.3750,True,False,0,True,False
787,788,0,3,8.0,4,1,29.1250,False,True,0,False,True
885,886,0,3,39.0,0,5,29.1250,False,True,0,True,False

In [68]:
# init pca object
pca = sklearn.decomposition.PCA(n_components=0.9999)
# apply pca
X_pca = pca.fit_transform(df)
# invert pca
X_ori = pca.inverse_transform(X_pca)
# define anomaly score as the sum of the absolute distances
anomaly_score = np.abs(df.to_numpy() - X_ori).sum(1)
# get last quantile
threshold = np.quantile(anomaly_score, 0.99)
# get ids of anomalous values
anomalous_ids = np.argwhere(anomaly_score > threshold).squeeze()

In [69]:
df.iloc[anomalous_ids]

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Sex_female,Sex_male
159,160,0,3,39.333333,8,2,69.5500,False,False,1,False,True
180,181,0,3,27.000000,8,2,69.5500,False,False,1,True,False
201,202,0,3,31.000000,8,2,69.5500,False,False,1,False,True
324,325,0,3,29.000000,8,2,69.5500,False,False,1,False,True
679,680,1,1,36.000000,0,1,512.3292,True,False,0,False,True
737,738,1,1,35.000000,0,0,512.3292,True,False,0,False,True
792,793,0,3,19.000000,8,2,69.5500,False,False,1,True,False
846,847,0,3,38.500000,8,2,69.5500,False,False,1,False,True
863,864,0,3,36.000000,8,2,69.5500,False,False,1,True,False

In [70]:
# first of all, split input variables from output variables
x = df[list(set(df.columns)-set(['Embarked_S']))]
y = df['Embarked_S']

In [71]:
# define standard scaler
scaler = sklearn.preprocessing.StandardScaler()
# normalize features
x = scaler.fit_transform(x)

In [72]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [73]:
print(x_train.shape)
print(x_test.shape)

(712, 11)
(179, 11)

In [74]:
rf = sklearn.ensemble.RandomForestClassifier(n_estimators=100)

In [75]:
rf.fit(x_train, y_train)

RandomForestClassifier()

In [76]:
# predict on test set
y_estim = rf.predict(x_test)

In [77]:
# compute confusion matrix
conf_mat = sklearn.metrics.confusion_matrix(y_test, y_estim)
conf_mat

array([[ 52,   0],
       [  0, 127]])

In [78]:
# compute accuracy
acc = sklearn.metrics.accuracy_score(y_test, y_estim)
acc

1.0